# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'ParticleAuthDemo_Scene' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	pod 'ParticleAuthService', '0.7.20.1'
	pod 'ParticleNetworkBase', '0.7.20.1'
  # Pods for ParticleAuthDemo_Scene

end
