# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'ParticleWalletConnectDemo' do
source 'https://github.com/CocoaPods/Specs.git'

  use_frameworks!
pod 'ParticleNetworkBase', '0.8.5.1'
pod 'ParticleWalletConnect', '0.8.5.1'
pod 'ParticleAuthService', '0.8.5.1'

pod 'SDWebImage'
pod 'SDWebImageWebPCoder'
end

post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    config.build_settings["ARCHS[sdk=iphonesimulator*]"] = "x86_64"
    config.build_settings["ARCHS[sdk=iphoneos*]"] = "arm64"
  end
  # This is necessary for Xcode 14, because it signs resource bundles by default
  # when building for devices.
  installer.target_installation_results.pod_target_installation_results
  .each do |pod_name, target_installation_result|
    target_installation_result.resource_bundle_targets.each do |resource_bundle_target|
      resource_bundle_target.build_configurations.each do |config|
        config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
      end
    end
  end
  
end
