platform :ios, '14.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'ParticleAuthDemo_Scene' do
  use_frameworks!
	pod 'ParticleAuthService', '1.4.1'
	pod 'ParticleNetworkBase', '1.4.1'

  # from 1.14.0 you need add this line.
  pod 'SwiftyUserDefaults', :git => 'https://github.com/SunZhiC/SwiftyUserDefaults.git', :branch => 'master'
end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
    config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      end
    end
  
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings["IPHONEOS_DEPLOYMENT_TARGET"] = "14.0"
    end
  end
  end
