# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'ParticleAuthDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
source 'https://github.com/CocoaPods/Specs.git'
  use_frameworks!
	pod 'ParticleAuthService', '0.14.5'
	pod 'ParticleNetworkBase', '0.14.5'
  # Pods for ParticleAuthDemo

end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
    end
  end
  
end
