platform :ios, '14.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'ParticleConnectExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'ParticleNetworkBase', '1.4.2'
  pod 'ParticleAuthService', '1.4.2'
  pod 'ParticleWalletAPI', '1.4.2'
  pod 'ParticleAA', '1.4.2'
  
  pod 'ConnectCommon', '0.2.20'
  pod 'ConnectEVMAdapter', '0.2.20'
  pod 'ConnectSolanaAdapter', '0.2.20'
  pod 'ConnectWalletConnectAdapter', '0.2.20'
  pod 'ConnectPhantomAdapter', '0.2.20'
  pod 'ParticleConnect', '0.2.20'
  pod 'ParticleAuthAdapter', '0.2.20'

  # from 1.14.0 you need add this line.
  pod 'SwiftyUserDefaults', :git => 'https://github.com/SunZhiC/SwiftyUserDefaults.git', :branch => 'master'
  # from 1.14.0, if you need ParticleWalletConnect, you should add this line.
  pod 'WalletConnectSwiftV2', :git => 'https://github.com/SunZhiC/WalletConnectSwiftV2.git', :branch => 'particle'
  
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
    config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      end
    end
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings["IPHONEOS_DEPLOYMENT_TARGET"] = "14.0"
    end
  end
end
