platform :ios, '14.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'ParticleConnectExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'ParticleNetworkBase', '2.0.3'
  pod 'ParticleNetworkChains', '2.0.3'
  pod 'ParticleWalletAPI', '2.0.3'
  pod 'ParticleAA', '2.0.3'
  pod 'ParticleWalletGUI', '2.0.3'
  pod 'ParticleWalletConnect', '2.0.3'
  
  pod 'ConnectCommon', '2.0.3'
  pod 'ConnectEVMAdapter', '2.0.3'
  pod 'ConnectSolanaAdapter', '2.0.3'
  pod 'ConnectWalletConnectAdapter', '2.0.3'
  pod 'ConnectPhantomAdapter', '2.0.3'
  pod 'ParticleConnect', '2.0.3'

  pod 'AuthCoreAdapter', '2.0.3'
  pod 'ParticleAuthCore', '2.0.3'
  pod 'ParticleMPCCore', '2.0.3'
  pod 'Thresh', '2.0.3'
  
  # from 1.14.0 you need add this line.
  pod 'SwiftyUserDefaults', :git => 'https://github.com/SunZhiC/SwiftyUserDefaults.git', :branch => 'master'
  # from 1.14.0, if you need ParticleWalletConnect, you should add this line.
  pod 'WalletConnectSwiftV2', :git => 'https://github.com/SunZhiC/WalletConnectSwiftV2.git', :branch => 'particle'
  # if you need ParticleAuthCore or ParticleWalletGUI, you should add this line.
  pod 'SkeletonView', :git => 'https://github.com/SunZhiC/SkeletonView.git', :branch => 'main'
      
  
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
    config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      end
    end

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings["IPHONEOS_DEPLOYMENT_TARGET"] = "14.0"
      end
    end
end
