platform :ios, '14.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'ParticleConnectExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'ParticleNetworkBase', '1.3.21'
  pod 'ParticleAuthService', '1.3.21'
  pod 'ParticleWalletAPI', '1.3.21'
  pod 'ParticleAA', '1.3.21'
  pod 'ParticleWalletGUI', '1.3.21'
  pod 'ParticleWalletConnect', '1.3.21'
  
  pod 'ConnectCommon', '0.2.18'
  pod 'ConnectEVMAdapter', '0.2.18'
  pod 'ConnectSolanaAdapter', '0.2.18'
  pod 'ConnectWalletConnectAdapter', '0.2.18'
  pod 'ConnectPhantomAdapter', '0.2.18'
  pod 'ParticleConnect', '0.2.18'
  pod 'ParticleAuthAdapter', '0.2.18'
  
  
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
    config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      end
    end

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings["IPHONEOS_DEPLOYMENT_TARGET"] = "14.0"
      end
    end
end
