# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'DemoObjc' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'
    pod 'ParticleWalletGUI', '0.12.0'
    pod 'ParticleWalletAPI', '0.12.0'
    pod 'ParticleNetworkBase', '0.12.0'
    pod 'ParticleAuthService', '0.12.0'
    pod 'ParticleWalletConnect', '0.12.0'
    pod 'ParticleConnect', '0.1.52'
    pod 'ConnectWalletConnectAdapter', '0.1.52'
    pod 'ConnectEVMAdapter', '0.1.52'
    pod 'ConnectSolanaAdapter', '0.1.52'
    pod 'ConnectPhantomAdapter', '0.1.52'
    pod 'ConnectCommon', '0.1.52'
    
    pod 'SkeletonView', :git => 'https://github.com/SunZhiC/SkeletonView.git', :branch => 'main'
    pod 'WalletConnectSwift', :git => 'https://github.com/SunZhiC/WalletConnectSwift', :branch => 'master'
    pod 'SwiftMessages', :git => 'https://github.com/SunZhiC/SwiftMessages', :branch => 'master'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
    config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      end
    end
  
  # This is necessary for Xcode 14, because it signs resource bundles by default
      # when building for devices.
      installer.target_installation_results.pod_target_installation_results
        .each do |pod_name, target_installation_result|
        target_installation_result.resource_bundle_targets.each do |resource_bundle_target|
          resource_bundle_target.build_configurations.each do |config|
            config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
          end
        end
      end
end
