platform :ios, '14.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'DemoObjc' do
  use_frameworks!
    pod 'ParticleWalletGUI', '1.3.9'
    pod 'ParticleWalletAPI', '1.3.9'
    pod 'ParticleNetworkBase', '1.3.9'
    pod 'ParticleAuthService', '1.3.9'
    pod 'ParticleWalletConnect', '1.3.9'
    pod 'ParticleAA', '1.3.9'
    
    pod 'ParticleAuthAdapter', '0.2.15'
    pod 'ParticleConnect', '0.2.15'
    pod 'ConnectWalletConnectAdapter', '0.2.15'
    pod 'ConnectEVMAdapter', '0.2.15'
    pod 'ConnectSolanaAdapter', '0.2.15'
    pod 'ConnectPhantomAdapter', '0.2.15'
    pod 'ConnectCommon', '0.2.15'
    
    pod 'SkeletonView', :git => 'https://github.com/SunZhiC/SkeletonView.git', :branch => 'main'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
    config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      end
    end
  
  # This is necessary for Xcode 14, because it signs resource bundles by default
      # when building for devices.
      installer.target_installation_results.pod_target_installation_results
        .each do |pod_name, target_installation_result|
        target_installation_result.resource_bundle_targets.each do |resource_bundle_target|
          resource_bundle_target.build_configurations.each do |config|
            config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
          end
        end
      end
end
