platform :ios, '14.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'ParticleAuthDemo' do
  use_frameworks!
	pod 'ParticleAuthService', '1.3.12'
	pod 'ParticleNetworkBase', '1.3.12'

end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
    end
  end
  
end
