# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'Demo' do
  use_frameworks!
  source 'https://github.com/CocoaPods/Specs.git'
    pod 'ParticleWalletGUI', '1.2.1'
    pod 'ParticleWalletAPI', '1.2.1'
    pod 'ParticleNetworkBase', '1.2.1'
    pod 'ParticleAuthService', '1.2.1'
    pod 'ParticleWalletConnect', '1.2.1'
    pod 'ParticleAA', '1.2.1'
    
    pod 'ParticleConnect', '0.2.12'
    pod 'ParticleAuthAdapter', '0.2.12'
    pod 'ConnectWalletConnectAdapter', '0.2.12'
    pod 'ConnectEVMAdapter', '0.2.12'
    pod 'ConnectSolanaAdapter', '0.2.12'
    pod 'ConnectPhantomAdapter', '0.2.12'
    pod 'ConnectCommon', '0.2.12'
    
    # if you use ParticleWalletGUI, you need add this line.
    pod 'SkeletonView', :git => 'https://github.com/SunZhiC/SkeletonView.git', :branch => 'main'
    # if you use ParticleWalletConnect or ConnectWalletConnectAdapter, you need add this line
    pod 'SwiftMessages', :git => 'https://github.com/SunZhiC/SwiftMessages', :branch => 'master'
end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
    config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      end
    end
  
  
  # This is necessary for Xcode 14, because it signs resource bundles by default
      # when building for devices.
      installer.target_installation_results.pod_target_installation_results
        .each do |pod_name, target_installation_result|
        target_installation_result.resource_bundle_targets.each do |resource_bundle_target|
          resource_bundle_target.build_configurations.each do |config|
            config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
          end
        end
      end
        
        
      installer.generated_projects.each do |project|
            project.targets.each do |target|
                target.build_configurations.each do |config|
                    config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
                 end
            end
     end
        
end
