# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'Demo' do
  use_frameworks!
  source 'https://github.com/CocoaPods/Specs.git'
    pod 'ParticleWalletGUI', '0.7.0'
  
end


post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    config.build_settings["ARCHS[sdk=iphonesimulator*]"] = "x86_64"
    config.build_settings["ARCHS[sdk=iphoneos*]"] = "arm64"
  end
end
